export const lightTheme = "light";
export const darkTheme = "dark";

export const workHistory = [
  {
    logo: "centrica-logo-square.png",
    url: "https://www.bordgaisenergy.ie/",
    position: "Senior Frontend Developer",
    companyName: "Centrica",
    positionType: "Contract",
    date: "June 2020 - March 2022",
    address: "22 Commercial St, Spitalfields, London E1 6LP",
    describe:
      "Worked as part of the digital team to create new features for the online portal for logged in users.Features included displaying information on customers energy usage, energy usage tracking with trends, sign up forms and customized offers for customers based on location and meter type. Liaising with backend end devs to hash out a contract for API calls and coordinating releases.",
  },
  {
    logo: "hugoandcat.jpeg",
    url: "https://www.hugoandcat.com/",
    position: "Senior Frontend Developer",
    companyName: "Hugo & Cat",
    positionType: "Contract",
    date: "Oct 2019 - Jan 2020",
    address: "22 Commercial St, Spitalfields, London E1 6LP",
    describe: "Working for one of their big clients (Dewalt, Stanly, Black and Decker) to rebuild the new customer-facing site.",
  },
  {
    logo: "pinnacle.jpeg",
    url: "https://www.cardifpinnacle.com/",
    position: "Senior Frontend Developer",
    companyName: "Cardif Pinnacle",
    positionType: "Contract",
    date: "Jun 2019 - Sep 2019",
    address: "Borehamwood, England, United Kingdom",
    describe:
      "Worked on a pet insurance platform with their partners J Sainsburys. We used webpack and react js for the front end and php for the back end and API calls. Worked for Cardif Pinnacle developing a new digital platform for managing insurance policies for a major retailer. Working in an Agile environment, working closely with designers, UX and marketing to reach day 1 release",
  },
  {
    logo: "reed.jpeg",
    url: "https://rxglobal.com/",
    position: "Senior Frontend Developer",
    companyName: "Reed Exhibitions",
    positionType: "Contract",
    date: "May 2017 - May 2019",
    address: "Richmond, London England, United Kingdom",
    describe:
      "Worked for Reed exhibitions which is a part of the RELX group. I joined the team at Reed when they started developing the new digital platform and helped them reach feature parity with the old platform. Reed Exhibitions have business units around the world, all business units had to be onboarded and catered for",
  },
  {
    logo: "direction-group.png",
    url: "https://tmwbusiness.com/",
    position: "Senior Frontend Developer",
    companyName: "Direction Group",
    positionType: "Contract",
    date: "March 2017 - April 2017",
    address: "Reading UK",
    describe: "Worked on dynamic HTML pages using Reactjs and static HTML emails, both needed to be responsive for a marketing campaign that the company was working on.",
  },
  {
    logo: "vm.jpeg",
    url: "https://www.virginmedia.com/",
    position: "Senior Frontend Developer",
    companyName: "Virgin Media",
    positionType: "Contract",
    date: "Sep 2014 - Dec 2016",
    address: "London UK",
    describe:
      "The UK's leading entertainment and broadband provider, I worked with a team of developers to make the site fully responsive, introduce development standards to make it easier to add to, maintain and debug code, use new technologies to give users a better experience, A/B testing and personalization to improve conversions",
  },
  {
    logo: "dhi_masthead.png",
    url: "https://www.digitalhealth.net/",
    position: "Web developer",
    companyName: "Digital Health Media",
    positionType: "Contract",
    date: "Oct 2012 - Sep 2014",
    address: "London UK",
    describe:
      "I worked as a web developer for a health IT news website. I used languages such as ColdFusion, Javascript, MySQL, HTML5, CSS3. I also worked with libraries such as Backbone, D3, Bootstrap and jquery",
  },
  {
    logo: "shopto.png",
    url: "https://www.shopto.net/",
    position: "PHP Developer",
    companyName: "ShopTo",
    positionType: "Contract",
    date: "July 2012 - Oct 2012",
    address: "Bracknell UK",
    describe:
      "ShopTo.net is an online games retailer. When I joined the company they were in the transition period of moving over from there old PHP site too and new site which now uses more modern technologies. I worked extensively on a Linux machine using PHP, Yii, MySQL and Svn.",
  },
  {
    logo: "mediacom.png",
    url: "https://www.mediacom.com/en",
    position: "Web developer",
    companyName: "Mediacom",
    positionType: "Contract",
    date: "Feb 2012 - Feb 2012",
    address: "London UK",
    describe:
      "For Mediacom I was coding HTML emails. I was given designs and I had to hand code them into HTML and CSS. I had to check the compatibility of the email in different browsers and email clients making sure that the email rendered consistently throughout",
  },
  {
    logo: "imeche.jpeg",
    url: "https://www.imeche.org/",
    position: "Web developer",
    companyName: "Institute of mechanical engineering",
    positionType: "Contract",
    date: "Nov 2011 - Jan 2012",
    address: "London UK",
    describe:
      "Worked with the Digital Marketing Manager to transfer and recode (HTML & CSS) the required content from the main website to the new cms (Sitefinity 4.3). The site had to be coded so that the site would render correctly for smartphones and other portable devices",
  },
  {
    logo: "emmas.jpeg",
    url: "https://www.emmasdiary.co.uk/",
    position: "Web developer",
    companyName: "Lifecycle marketing",
    positionType: "Contract",
    date: "Oct 2010 - Nov 2011",
    address: "Marlow UK",
    describe:
      "I worked on the www.emmasdiary.co.uk website on a daily basis. I helped migrate the old site from the TRA CMS to the new Sitefinity CMS. I learned how to use Sitefinity and then taught the less technical members of staff how to use it",
  },
];

export const repoWork = [
  {
    mainImage: "tetris/main.PNG",
    leftImage: "tetris/board.PNG",
    rightImage: "tetris/save.PNG",
    liveDemo: "https://react-tetris-red.vercel.app/",
    repoUrl: "https://github.com/MoAnsir/react-tetris",
    title: "Tetris game",
    mainText: "Tetris game with speed slider",
    leftText: "Score board and leader board",
    rightText: "On game over save your score",
  },
  {
    mainImage: "isaPots/main.PNG",
    leftImage: "isaPots/dark.PNG",
    rightImage: "isaPots/add.PNG",
    liveDemo: "https://investment-pot.vercel.app/",
    repoUrl: "https://github.com/MoAnsir/Investment-pot",
    title: "ISA Investment pot",
    mainText: " investment pot tracker that will allow users to make payments into their investment pots",
    leftText: "Score board and leader board",
    rightText: "On game over save your score",
  },
  {
    mainImage: "nft/nft.PNG",
    leftImage: "nft/mint.PNG",
    rightImage: "nft/localhostSetup.PNG",
    liveDemo: "",
    repoUrl: "https://github.com/MoAnsir/nft_mint_machine",
    title: "NFT mint on Ethereum",
    mainText: "NFT mint machine on Eth test network using IPFS",
    leftText: "Score board and leader board",
    rightText: "On game over save your score",
  },
  {
    mainImage: "note2/main.PNG",
    leftImage: "note2/edit.PNG",
    rightImage: "note2/list.PNG",
    liveDemo: "https://noteappusecontext.vercel.app/",
    repoUrl: "https://github.com/MoAnsir/noteappusecontext",
    title: "Note app",
    mainText: "note taking app that saves data to IndexDB with useContext for state",
    leftText: "Worked as part of the digital",
    rightText: "Worked as part of the digital",
  },
  {
    mainImage: "expense/main.PNG",
    leftImage: "expense/edit.PNG",
    rightImage: "expense/chart.PNG",
    liveDemo: "https://expense-tracker-nine-khaki.vercel.app/",
    repoUrl: "https://github.com/MoAnsir/Expense_Tracker",
    title: "Expense Tracker",
    mainText: "Track your expenses",
    leftText: "Edit modal",
    rightText: "Example of the charts",
  },
  {
    mainImage: "note1/main.PNG",
    leftImage: "note1/edit.PNG",
    rightImage: "note1/add.PNG",
    liveDemo: "https://noteapp-weld.vercel.app/",
    repoUrl: "https://github.com/MoAnsir/noteapp",
    title: "Todo list",
    mainText: "Note app that uses IndexDB",
    leftText: "Score board and leader board",
    rightText: "On game over save your score",
  },
];
